<cfoutput>
<!---
	Markup for just before `</body>`.

	Author-supplied extra markup first, then the site's first-visit notice.
	Its own file rather than a second branch inside `_head.cfm`, because a
	theme includes them in two different places and one of them is easy to
	forget. Extra markup is emitted raw by design — see
	PageService.applyRawMarkup for the `content.unfiltered` gate. The notice
	is generated by Core from settings, so a theme that already includes this
	file gets the dialog without changing.
--->
<cfset local.seo = args.seo ?: {}>
<cfif len( local.seo.bodyMarkup ?: "" )>
	#local.seo.bodyMarkup#
</cfif>
<cfinclude template="/core/views/frontend/_notice.cfm">
</cfoutput>
